model:
  iterations: 2
  api_use: true
  pre_func_use: true
  related_attrs: true
  func_use: true
  enhanced_use: true
  n_method: '5%'
  distri_analysis: false
  err_gen_use: false
  guide_use: false
  rel_top: 2
  run_info: '0Following results running with rereading (after running, if result not idea, suggest rereading, as file reading problem)'
  func_val_threshold: 0.5

read:
  pre_func: true
  related_attrs: true
  cluster: true
  error_checking: true
  extra_all_label: false
  func: true
  enhanced: false
  distri_analysis: false
  guide: false
  err_gen: false
  read_in_batch: false
  start_time: '02-14-19:32'  
  end_time: '02-14-22:23'  

data:
  base_dir: '.'
  err_rate_list: ["01"] #["mixed_err", "typos", "missing_values", "pattern_violations", "rule_violations", "outliers"]
  all_set_num: 1
  datasets: ['flights']
  err_check_val_num_per_query: 20
  result_dir: 'pipeline'
  

read_paths:
  flights01-1: './result/pipeline/11-11 flights01-5%-set1-iterations1/'
  # flights01-1: './result/pipeline/02-08 flights01-5%-set1/'
  # flights01-2: './result/pipeline/02-08 flights01-5%-set2/'
  # flights01-3: './result/pipeline/02-08 flights01-5%-set3/'
  # flights01-4: './result/pipeline/02-08 flights01-5%-set4/'
  # flights01-5: './result/pipeline/02-08 flights01-5%-set5/'
  hospital01-1: './result/pipeline/10-28 hospital01-5%-set1/'