model:
  api_use: true
  pre_func_use: true
  related_attrs: true
  distri_analysis: true
  guide_use: true
  func_use: true
  n_method: '5%'
  err_gen_use: true
  rel_top: 2
  run_info: '0Following results running with rereading (after running, if result not idea, suggest rereading, as file reading problem)'

read:
  pre_func: false
  distri_analysis: false
  related_attrs: false
  cluster: false
  guide: false
  error_checking: false
  func: false
  err_gen: false
  read_in_batch: false
  start_time: '02-14-19:32'  
  end_time: '02-14-22:23'  

data:
  base_dir: '.'
  err_rate_list: ["mixed_err", "typos", "missing_values", "pattern_violations", "rule_violations", "outliers"]
  all_set_num: 1
  datasets: ['hospital']
  err_check_val_num_per_query: 20
  result_dir: 'pipeline'
  

read_paths:
  flights01-1: './result/pipeline/02-08 flights01-5%-set1/'
  flights01-2: './result/pipeline/02-08 flights01-5%-set2/'
  flights01-3: './result/pipeline/02-08 flights01-5%-set3/'
  flights01-4: './result/pipeline/02-08 flights01-5%-set4/'
  flights01-5: './result/pipeline/02-08 flights01-5%-set5/'